blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/storyleaps/bobninja-webscribe/blob/master/README.md
    about: Please read the documentation before opening an issue.
